services:  
  - type: web    
    name: hamster-generator    
    env: python    
    buildCommand: "pip install -r requirements.txt"    
    startCommand: "python app.py"  
     plan: free
    deploy:
      branch: main
